openapi: 3.1.0
info:
  title: Aegis Backend API
  description: API for Aegis Backend user management
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/api/auth'
    description: Local development server
  - url: 'https://api.aegis.example.com/api/auth'
    description: Production server

paths:
  /register:
    post:
      summary: Register a new user
      description: Creates a new user account with the provided credentials
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                  example: user@example.com
                password:
                  type: string
                  format: password
                  description: User's password (min 6 characters)
                  minLength: 6
                  example: securePassword123
                name:
                  type: string
                  description: User's full name
                  example: John Doe
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User registered successfully
        '400':
          description: Bad Request - Missing required fields or user already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User already exists
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Server error